### ISSUE TITLE
Question: why dotnet-load-tester

### ISSUE THREAD

**Issue by donifer** [bricef/gitops-tutorial#1]
Hey @bricef, thanks for the tutorial!

I have one question, why do we use:
```
metadata:
  name: podinfo
  annotations:
    flux.weave.works/tag.dotnet-load-tester: glob:*
    flux.weave.works/automated: 'true'
```

Shouldn't it be `flux.weave.works/tag.podinfo: glob:*`? Or does it not matter? I'm not sure where `dotnet-load-tester` came from.

Thanks!
